const aboutNav = () => {
    const contentContainer = document.querySelector("#content");
    contentContainer.replaceChildren();
    const welcomeHeading = document.createElement("h1");
    welcomeHeading.classList.add("welcome-heading");
    welcomeHeading.textContent = "Meet our Noah's Ark family";
    const aboutContent = document.createElement("div");
    aboutContent.classList.add("about-content");
    const chef = document.createElement("div");
    chef.classList.add("chef");
    const chefTitle = document.createElement("h3");
    chefTitle.textContent = "Noah - Owner/Chef";
    const chefInfo = document.createElement("p");
    chefInfo.textContent = "I created this place to feed good food to good people and tell my story.";
    const manager = document.createElement("div");
    manager.classList.add("manager");
    const managerTitle = document.createElement("h3");
    managerTitle.textContent = "Mrs. Noah - General Manager";
    const managerInfo = document.createElement("p");
    managerInfo.textContent = "I've been by Noah's side since before the flood and this place is no different.";
    const waitStaff = document.createElement("div");
    waitStaff.classList.add("wait-staff");
    const waitOneTitle = document.createElement("h3");
    waitOneTitle.textContent = "Shem - Head Waiter";
    const waitTwoTitle = document.createElement("h3");
    waitTwoTitle.textContent = "Ham - Waiter";
    const waitThreeTitle = document.createElement("h3");
    waitThreeTitle.textContent = "Japheth - Waiter";
    const waitStaffInfo = document.createElement("p");
    waitStaffInfo.textContent = "We're always here for dad, even if it means waiting tables. At least we get to meet new people.";
    chef.appendChild(chefTitle);
    chef.appendChild(chefInfo);
    manager.appendChild(managerTitle);
    manager.appendChild(managerInfo);
    waitStaff.appendChild(waitOneTitle);
    waitStaff.appendChild(waitTwoTitle);
    waitStaff.appendChild(waitThreeTitle);
    waitStaff.appendChild(waitStaffInfo);
    aboutContent.appendChild(chef);
    aboutContent.appendChild(manager);
    aboutContent.appendChild(waitStaff);
    contentContainer.appendChild(welcomeHeading);
    contentContainer.appendChild(aboutContent);
};

export default aboutNav;